#!/usr/bin/env bash
# Generates UID→username relabel rules in loki-journal.alloy between the
# BEGIN/END UID MAP markers, based on the local system's passwd database.
#
# Usage: run on the target server after deploying the config files:
#   ./scripts/generate-uid-map.sh [path/to/loki-journal.alloy]

set -euo pipefail

ALLOY_FILE="${1:-$(dirname "$0")/../loki-journal.alloy}"

if [[ ! -f "$ALLOY_FILE" ]]; then
  echo "error: $ALLOY_FILE not found" >&2
  exit 1
fi

# Build the replacement block
RULES=""
while IFS=: read -r username _ uid _; do
  RULES+="  rule {\n"
  RULES+="    source_labels = [\"__journal__systemd_owner_uid\"]\n"
  RULES+="    regex         = \"${uid}\"\n"
  RULES+="    replacement   = \"${username}\"\n"
  RULES+="    target_label  = \"owner\"\n"
  RULES+="  }\n"
done < <(getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 { print $1, $2, $3, $4 }' OFS=:)

BEGIN_MARKER="  // BEGIN UID MAP - generated by scripts/generate-uid-map.sh - do not edit manually"
END_MARKER="  // END UID MAP"

# Replace everything between the markers (inclusive) with new content
perl -0777 -i -pe \
  "s|\Q${BEGIN_MARKER}\E\n.*?\Q${END_MARKER}\E|${BEGIN_MARKER}\n${RULES}${END_MARKER}|s" \
  "$ALLOY_FILE"

echo "Updated $ALLOY_FILE"
echo "Reload alloy: systemctl reload alloy"
